#!/bin/sh
if [ $# != 1 ]; then
    echo "usage : $0 path"; exit
fi
NewPath=`readlink -f $1`; shift
RC=~/.`basename $SHELL`rc
if ! grep PATH= $RC | sed -e s/.*PATH=/:/ -e s/\"//g \
    -e s#\$HOME#$HOME#g -e s/$/:/ | grep :$NewPath: > /dev/null
then
    echo PATH=\"\$PATH:$NewPath\" | sed s#$HOME#\$HOME#g >> $RC
fi
