#!/bin/bash
LANG=en_US.UTF-8
if [ `getconf LONG_BIT` != 64 ]; then
    echo "You should run this script on x86_64 CPU architecture."
    exit 1
fi
if [ `uname -m` = x86_64 ]; then exit; fi   # 64-bit OS
cat /proc/cpuinfo | egrep ' lm( |$)' > /dev/null
