#!/bin/bash
LANG=C
if [ $# -eq 0 ]; then
	echo -e "\nCheck commands\n\n" \
	"usage : $0  command:project [command:project [..]]]\n"
	exit -1
fi
for inf in $* ; do
	 app=`echo $inf | cut -d : -f 1`
	proj=`echo $inf | cut -d : -f 2`
	if ! which $app > /dev/null; then
    	cat - << EOF

$app is absent.

Please visit my projects in the following URL,
and install it according to the README.md.

    https://github.com/leorge/$proj

EOF
    	exit -1
	fi
done
