#!/bin/bash
for app in $*; do
    if ! which $app > /dev/null; then
        echo "Install $app..."
        if which apt > /dev/null; then
            sudo apt install -y $app
        elif which dnf > /dev/null; then
            sudo dnf install -y $app
        fi
    fi
done
