#!/bin/bash
NULL=/dev/null
for app in $*; do
    if ! which $app 2> $NULL; then
        echo -n "Install $app..." 1>&2
        #### debian #### 
        if which apt 2> $NULL; then
            sudo apt install -y $app
        elif which apt-get 2> $NULL; then
            sudo apt-get install -y $app
        elif which aptitude 2> $NULL; then
            sudo aptitude install -y $app
        #### redhat #### 
        elif which dnf 2> $NULL; then
            sudo dnf install -y $app.x86_64
#        elif which yum 2> $NULL; then
#            sudo yum install -y $app
        else
			echo " failed." 1>&2
            exit
        fi
		echo "" 1>&2
    fi
done
