#!/bin/bash
if [ $# -eq 0 ]; then
	echo " `basename $0` install serveral commands."
	echo " usage : $0 command1 [command2 [ .... ]]"
	exit
fi
NULL=/dev/null
for app in $*; do
    if ! which $app > $NULL; then
        echo -n "Install $app..." 1>&2
        unset ERR
        #--- debian ---- 
        if which apt 2> $NULL; then
            sudo apt install -y $app
        elif which apt-get 2> $NULL; then
            sudo apt-get install -y $app
        elif which aptitude 2> $NULL; then
            sudo aptitude install -y $app
        #--- redhat ---- 
        elif which dnf 2> $NULL; then
            sudo dnf install -y $app.x86_64
#        elif which yum 2> $NULL; then
#            sudo yum install -y $app
        else
            ERR=$?
            echo " failed." 1>&2
            exit $ERR
        fi
        #### Check result ####
        ERR=$?; if [ $ERR -ne 0 ]; then exit $ERR; fi
        echo "" 1>&2
    fi
done
